## Упражнения по библиотеке Numpy

In [2]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [17]:
#done
a = np.random.random(10)*10
a[(a > 3) & (a < 8)] *= -1
print(a)

[-3.83964786  1.72449226  2.20915243 -6.48953686  9.46599183 -7.84102425
 -3.15011102 -5.64034436 -4.4898556  -6.68315178]


**2.** Заменить максимальный элемент случайного массива на 0

In [15]:
#done
a = np.random.random(10)*10
print(a)
a[a.argmax()] = 0
print(a)

[0.67460014 6.76492016 5.66053357 7.70929865 6.76745105 5.52514478
 5.79715719 6.45128465 7.07308565 8.72617077]
[0.67460014 6.76492016 5.66053357 7.70929865 6.76745105 5.52514478
 5.79715719 6.45128465 7.07308565 0.        ]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [26]:
#done
a = np.random.randint(1, 11, size=(2, 4))
print(a)
arr1 = a[1, :]
arr2 = a[0, :]
res = arr1.dot(arr2)
print(res)

[[5 3 4 4]
 [8 7 7 9]]
125


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [166]:
#done
a = np.random.randint(1, 11, size=(8, 3))
b = np.random.randint(1, 11, size=(2, 2))
print(a)
print(b)

row_to_check = np.array([[b[0][0], b[1][0]], [b[0][0], b[1][1]], [b[0][1], b[1][0]], [b[0][1], b[1][1]],
               [b[1][0], b[0][0]], [b[1][1], b[0][0]], [b[1][0], b[0][1]], [b[1][1], b[0][1]]])    

is_row_in_matrix = np.isin(a, row_to_check)
print(is_row_in_matrix)

res = []
for i in range(len(is_row_in_matrix)):
    if np.count_nonzero(is_row_in_matrix[i] == True) > 1:
        res.append(i)
    
result = a[res]

print(result)

[[ 1  9  3]
 [ 9  2 10]
 [ 6  4  5]
 [ 6  4  9]
 [ 1  5  7]
 [ 8  1  2]
 [ 6  7  3]
 [ 1  7  7]]
[[9 7]
 [2 9]]
[[False  True False]
 [ True  True False]
 [False False False]
 [False False  True]
 [False False  True]
 [False False  True]
 [False  True False]
 [False  True  True]]
[[ 9  2 10]
 [ 1  7  7]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [57]:
#done
matr = np.array([[2,2,3],
        [3,3,3],
        [0,0,0],
        [2,1,3],
        [2,2,3],
        [3,3,3],
        [7,8,7],
        [5,5,5],
        [3,3,3],
        [2,2,3]])


result = np.where((matr[:, 0] != matr[:, 1])
                          | (matr[:, 0] != matr[:, 2]))

print(matr[result])

[[2 2 3]
 [2 1 3]
 [2 2 3]
 [7 8 7]
 [2 2 3]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [5]:
#done
matr =  np.array([[2,2,3],
        [3,3,3],
        [0,0,0],
        [2,1,3],
        [2,2,3],
        [3,3,3],
        [7,8,7],
        [5,5,5],
        [3,3,3],
        [2,2,3]])

_, indices = np.unique(matr, axis=0, return_index=True)

result = matr[np.sort(indices)]

print(result)

[[2 2 3]
 [3 3 3]
 [0 0 0]
 [2 1 3]
 [7 8 7]
 [5 5 5]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [12]:
#done

# numpy
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) 

not_null_diag = np.diagonal(X)[np.diagonal(X) != 0]

result = np.prod(not_null_diag)

print(result)

# python
X = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]

diag_len = min(len(X), len(X[0]))
for i in range(diag_len):
    res = 1     
    if X[i][i] != 0:
        res *= X[i][i]

if res == 1:
    print('No such elements')
else:
    print(res)

3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [47]:
#done

# numpy

x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

x_unique, x_counts = np.unique(x, return_counts=True)
y_unique, y_counts = np.unique(y, return_counts=True)

res = True

if (np.shape(x_unique) != np.shape(y_unique)):
    res = False
if (np.any(x_unique != y_unique) or np.any(x_counts != y_counts)):
    res =  False
    
print(res)


# python

x = [1, 2, 2, 4]
y = [4, 2, 1, 2]

if len(x) != len(y):
    res = False

x.sort()
y.sort()

for i in range(len(x)):
    if x[i] != y[i]:
        res = False
    else:
        res = True
print(res)

True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [45]:
#done

# numpy

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

zero_indices = np.where(x==0)

if len(x) > (zero_indices[0][-1] + 1):
    zero_indices[0] += 1
else:
    zero_indices[0][:-1] += 1
    
if len(zero_indices[0]) <= 1 or all(i == 0 for i in x):
    print(f'No max element')
else:
    print(f'Max element after zeros: {np.max(x[zero_indices[0]])}')


#python

x = [0, 0, 0, 0, 0, 0, 0, 0, 0]

elements = []

if x[-1] == 0:
    for i in range(len(x) - 1):
        if x[i] == 0:
            elements.append(x[i+1])
else:
    for i in range(len(x)):
        if x[i] == 0:
            elements.append(x[i+1])
            
if len(elements) <= 1 or all(el == 0 for el in elements):
    print('No max element')
else:
    print(f'Max element after zeros: {max(elements)}')

Max element after zeros: 5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [126]:
#done
#numpy
x = np.array([2, 2, 2, 3, 3, 3, 5])

diff_x = np.diff(x)

diff_bool = np.append(True, diff_x != 0) 
numbers = x[diff_bool]

num_index = np.where(diff_bool)[0] 
num_index = np.append(num_index, len(x))
quantities = np.diff(num_index) 
print(f'Числа: {numbers}')
print(f'Частоты: {quantities}')

# python
x = [2, 2, 2, 3, 3, 3, 5]
counter = 1
numbers = []
quantity = []
for i in range(1, len(x)):
    if (x[i] == x[i-1]):
        counter += 1
    elif x[i] != x[i-1]:
        quantity.append(counter)
        numbers.append(x[i-1])
        counter = 1
    if (i == len(x) - 1) and (x[i] == x[i-1]):
        quantity.append(counter)
    elif (i == len(x) - 1) and (x[i] != x[i-1]):
        numbers.append(x[i])
        quantity.append(counter)
        
print(f'Числа: {numbers}')
print(f'Частоты: {quantity}')

Числа: [2 3 5]
Частоты: [3 3 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [113]:
import scipy
import timeit
import math

In [174]:
#done
# Numpy
X = np.array([[1, 2, 3, 4], [4, 3, 2, 1]])
Y = np.array([[5, 6, 7, 8], [8, 7, 6, 5]])
 
def test1():
    return np.sqrt(np.sum((X[:, np.newaxis]-Y) ** 2, axis=-1))
 
def test2():
    return scipy.spatial.distance.cdist(X, Y)

print(test1())
print(test2())

time1 = timeit.timeit("test1()", setup="from __main__ import test1", number=1)
time2 = timeit.timeit("test2()", setup="from __main__ import test2", number=1)

if time1 < time2:
    print('NumPy быстрее')
else:
    print('SciPy быстрее')
    
print(time1)
print(time2)


# python

X = [[1, 2, 3, 4], [4, 3, 2, 1]]
Y = [[5, 6, 7, 8], [8, 7, 6, 5]]

def test3():
    result_matrix = []

    for x_row in X:
        row_distances = []
        for y_row in Y:
            distance = math.sqrt(sum((x - y) ** 2 for x, y in zip(x_row, y_row)))
            row_distances.append(distance)
        result_matrix.append(row_distances)

    return result_matrix

def test4():
    return scipy.spatial.distance.cdist(X, Y)

time3 = timeit.timeit("test3()", setup="from __main__ import test3", number=1)
time4 = timeit.timeit("test4()", setup="from __main__ import test4", number=1)

if time3 < time4:
    print('SciPy медленнее')
else:
    print('SciPy быстрее')
    
print(time3)
print(time4)

[[8.         9.16515139]
 [9.16515139 8.        ]]
[[8.         9.16515139]
 [9.16515139 8.        ]]
NumPy быстрее
5.949998740106821e-05
0.00028929999098181725


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [77]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [130]:
calorie_stats = np.loadtxt("cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [134]:
average_calories = np.mean(calorie_stats).round(2)
diff = (average_calories - 60).round(2)
print(f'Среднее количество калорий у конкурентов: {average_calories}')
print(f'Разница: {diff}')

Среднее количество калорий у конкурентов: 106.88
Разница: 46.88


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [135]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [136]:
median_calories = np.median(calorie_stats)
median_calories

110.0

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [165]:
nth_percentile = np.percentile(calorie_stats, 4)
nth_percentile

70.0

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [156]:
((np.sum(calorie_stats > 60) / calorie_stats.size) * 100).round(1)

96.1

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [159]:
calorie_std = np.std(calorie_stats).round(2)
calorie_std

19.36

In [160]:
# Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?
# Мне кажется, что вопрос поставлен не совсем корректно, т.к. если речь идёт о разбросе, то должен быть некий интервал,
# а не конкретное число. Чтобы узнать, какое количество калорий преобладает среди конкурентов мы можем обратиться к медиане
from scipy import stats as st
mode_calories = st.mode(calorie_stats)
mode_calories


C:\Users\USER\AppData\Local\Temp\ipykernel_24108\755014806.py:5: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode_calories = st.mode(calorie_stats)


ModeResult(mode=array([110.]), count=array([29]))

In [163]:
# Делаем вывод, что преобладает количество конкурентов со 110 калориями (29/77), а не со 100.
# Возвращаясь к стандартному отклонению можем сделать вывод: наш показатель равный 60 калориям лежит между 2-мя и 3-мя
# стандартными отклонениями, что ещё раз подчёркивает значительное отклонение от среднего показателя среди конкурентов
average_calories - 2 * calorie_std > 60
average_calories - 3 * calorie_std < 60

True

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [167]:
# С показателем в 60 калорий наши хлопья бьют практически всех конкурентов, входя в топ 4% лучших.
# Маркетологи смогут смело утверждать, что 9/10 ̶с̶т̶о̶м̶а̶т̶о̶л̶о̶г̶о̶в̶  диетологов рекомедуют хлопья CrunchieMunchies.
# Хочется лишь выдвинуть гипотезу, что при изменении названия на CrunchieMunchie ('Кранчи Мунчи') у потребителей может возникнуть
# ассоциация с одной популярной серией фильмов из нулевых, которая, возможно, поднимет продажи.